### ISSUE TITLE
Panel scaffolding

### ISSUE THREAD

**Issue by ghost** [a10networks/a10-horizon#24]
As an A10 Horizon developer, I would like there to be an existing set of modules, panels, and related so I can more easily take a story and begin working on it without impediments.
*\* Acceptance Criteria **
- Project/User Panels
- [ ] A10 Networks Scalable Load Balancing Overview
- [x] LB Instances (see #16)
- [ ] VIPs - (see #18)
- [ ] Scaling Groups - (see #19)
- [ ] Scaling Policies - already exists, enhancements.
- [ ] Certificates (see #17 )
- Admin Panels
- [x]  A10 Networks SLB Admin Overview
- [x] LB Instances (see #22)
- [x] VIPs (see #23)
- [x] Scaling Groups - already exists, enhancements.
- Cleanup and details
  Make copyright statements consistent.  Templates, too.
  Logo'ify headers.
  The A10 panel in the respective dashboards will have all of their templates stored in a single root-level directory to reduce the number of applications being added to Django's configuration.

**Comment by ghost** [comment]
Bumped this from a 3 to a 5 as there's a LOT of work to be done.  Most of it is easy work, but there's  a lot of it.  At first I thought "I'll just throw some panels and tabs together" but we need actions as well... which requires creating panels, tabs, tables, views, lots.

**Comment by ghost** [comment]
The "scaffolding" portion has been completed and we've moved on to fleshing out the functionality and getting all our features supported.
